### PR TITLE
Update remote_command_execution_vulnerability.py

### PR DESCRIPTION
**Pull request by haotian2004**
fix

### CODE REVIEW

**Comment by acecilia** [comment]
Hi 👋 
What is this PR fixing?

**Comment by haotian2004** [comment]
Your code is not very standard here
你这代码不太规范

**Comment by acecilia** [comment]
Well, adding a space on the right of the equal is not making it any more standard I think 😄

**Comment by haotian2004** [comment]
But that seems more formal

**Comment by acecilia** [comment]
Happy to accept any PR that fixes something or adds functionality 🙌  But formatting is very opinionated, better not change the code just based on that

**Pull request closed without merging**
